[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/alepar/wavething-cross-rs:aarch64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/alepar/wavething-cross-rs:x86_64-unknown-linux-gnu"