FROM rustembedded/cross:x86_64-unknown-linux-gnu-0.2.1

RUN dpkg --add-architecture amd64 && \
    apt-get update && \
    apt-get install --assume-yes \
        pkg-config \
        libdbus-1-dev:amd64