# Instruction + template repo: https://github.com/FedericoPonzi/rust-ci
# https://gist.github.com/Tehnix/5209b8fefd368bfdb67ca8761d3b8009
name: cross

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    name: deploy
    #    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ aarch64-unknown-linux-gnu, x86_64-unknown-linux-gnu ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          #strip target/${{ matrix.target }}/release/wavething-rust
          cd target/${{ matrix.target }}/release          
          tar czvf ../../../wavething-rust-${{ matrix.target }}.tar.gz wavething-rust
          cd -
      - name: Publish
        uses: softprops/action-gh-release@v1
        # TODO: if any of the build step fails, the release should be deleted.
        with:
          files: 'wavething-rust*'
          tag_name: "${{github.ref_name}}-${{ github.sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}
