name: 'Build and publish docker images (all platforms)'

on:
  workflow_dispatch:
  push:
    branches:
      - '**'  # every branch
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
